version: '3.3'
services:

  db:
    env_file:
      - ./.env
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    restart: always


  backend:
    # image: myxadin07/foodgram_backend:latest
    build: ../foodgram_backend
    restart: always
    volumes:
      - static_value:/app/backend/static/
      - media_value:/app/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: myxadin07/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  static_value:
  media_value:

#sd