# Generated by Django 3.2 on 2023-06-09 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favorite_Recipes',
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть не меньше 1')], verbose_name='Количество ингрединта (в граммах или штуках)'),
        ),
    ]
